"""add email, department and hire_date fields

Revision ID: 7c6cbbb9b392
Revises: c49065bf291e
Create Date: 2025-04-05 21:47:24.824271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6cbbb9b392'
down_revision = 'c49065bf291e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hire_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.create_unique_constraint('uq_employees_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('hire_date')
        batch_op.drop_column('department')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
